// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFM5gKyeFaJf_CnnHrwrBwIEh6qkQ96qk',
    appId: '1:347152255221:web:d1c6f435fa1cc4a4f91dbc',
    messagingSenderId: '347152255221',
    projectId: 'pichoy',
    authDomain: 'pichoy.firebaseapp.com',
    storageBucket: 'pichoy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3JEifYKCtX0n8gvAtu7dObA2qfvg9iSY',
    appId: '1:347152255221:android:63b6898b94690288f91dbc',
    messagingSenderId: '347152255221',
    projectId: 'pichoy',
    storageBucket: 'pichoy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2vjHGD1-g3qKE7jRWtEviyK_MorYWbds',
    appId: '1:347152255221:ios:2bd3e89b4b9bddeaf91dbc',
    messagingSenderId: '347152255221',
    projectId: 'pichoy',
    storageBucket: 'pichoy.appspot.com',
    iosBundleId: 'com.example.penulisanIlmiahApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2vjHGD1-g3qKE7jRWtEviyK_MorYWbds',
    appId: '1:347152255221:ios:2bd3e89b4b9bddeaf91dbc',
    messagingSenderId: '347152255221',
    projectId: 'pichoy',
    storageBucket: 'pichoy.appspot.com',
    iosBundleId: 'com.example.penulisanIlmiahApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFM5gKyeFaJf_CnnHrwrBwIEh6qkQ96qk',
    appId: '1:347152255221:web:f1efdeb6dea9c86ff91dbc',
    messagingSenderId: '347152255221',
    projectId: 'pichoy',
    authDomain: 'pichoy.firebaseapp.com',
    storageBucket: 'pichoy.appspot.com',
  );
}
